const { Router } = require("express");
const { crearPlan, crearOrden, listarPlanes, listarOrdenes, actualizarPlan, actualizarOrden } = require("../../controllers/Operaciones/planesTrabajo");
const documentos = require("../../controllers/Documentos/generarPdf");
const router = Router();
router.post("/planes-trabajo/desde-cotizacion/:cotizacionId", crearPlan);
router.post("/ordenes-internas/desde-plan/:planId", crearOrden);
router.get("/planes-trabajo", listarPlanes);
router.get("/ordenes-internas", listarOrdenes);
router.patch("/planes-trabajo/:id", actualizarPlan);
router.patch("/ordenes-internas/:id", actualizarOrden);
router.post("/planes-trabajo/:id/pdf", documentos.plan);
router.post("/ordenes-internas/:id/pdf", documentos.orden);
module.exports = router;
